// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwwzD7ZQvNpTTtzPMN7T5HCfy24MOiVk0',
    appId: '1:770427347098:web:33028a7126786f364dff23',
    messagingSenderId: '770427347098',
    projectId: 'dnd-app-87ffe',
    authDomain: 'dnd-app-87ffe.firebaseapp.com',
    databaseURL: 'https://dnd-app-87ffe-default-rtdb.firebaseio.com',
    storageBucket: 'dnd-app-87ffe.firebasestorage.app',
    measurementId: 'G-J9J2M5F0JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKYNZOiWyTvCVXaO2w5jRpDit4NM_OKuw',
    appId: '1:770427347098:android:75867966e2e8b1f94dff23',
    messagingSenderId: '770427347098',
    projectId: 'dnd-app-87ffe',
    databaseURL: 'https://dnd-app-87ffe-default-rtdb.firebaseio.com',
    storageBucket: 'dnd-app-87ffe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANDGfuRBDXjGYwNTvkNIauy2X3ok4WxLQ',
    appId: '1:770427347098:ios:c6b53e0dd4ecc4cf4dff23',
    messagingSenderId: '770427347098',
    projectId: 'dnd-app-87ffe',
    databaseURL: 'https://dnd-app-87ffe-default-rtdb.firebaseio.com',
    storageBucket: 'dnd-app-87ffe.firebasestorage.app',
    iosBundleId: 'com.dndApp.es',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANDGfuRBDXjGYwNTvkNIauy2X3ok4WxLQ',
    appId: '1:770427347098:ios:7f6115148e47f9594dff23',
    messagingSenderId: '770427347098',
    projectId: 'dnd-app-87ffe',
    databaseURL: 'https://dnd-app-87ffe-default-rtdb.firebaseio.com',
    storageBucket: 'dnd-app-87ffe.firebasestorage.app',
    iosBundleId: 'com.example.dndApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwwzD7ZQvNpTTtzPMN7T5HCfy24MOiVk0',
    appId: '1:770427347098:web:016ae0751c7219464dff23',
    messagingSenderId: '770427347098',
    projectId: 'dnd-app-87ffe',
    authDomain: 'dnd-app-87ffe.firebaseapp.com',
    databaseURL: 'https://dnd-app-87ffe-default-rtdb.firebaseio.com',
    storageBucket: 'dnd-app-87ffe.firebasestorage.app',
    measurementId: 'G-JLRKBNDMVV',
  );
}
