import 'package:flutter_quill/flutter_quill.dart';

/* 
  multiRowsDisplay: true,
  showDividers: true,
  showFontFamily: true,
  showFontSize: true,
  showBoldButton: true,
  showItalicButton: true,
  showSmallButton: false,
  showUnderLineButton: true,
  showLineHeightButton: false,
  showStrikeThrough: true,
  showInlineCode: true,
  showColorButton: true,
  showBackgroundColorButton: true,
  showClearFormat: true,
  showAlignmentButtons: false,
  showLeftAlignment: true,
  showCenterAlignment: true,
  showRightAlignment: true,
  showJustifyAlignment: true,
  showHeaderStyle: true,
  showListNumbers: true,
  showListBullets: true,
  showListCheck: true,
  showCodeBlock: true,
  showQuote: true,
  showIndent: true,
  showLink: true,
  showUndo: true,
  showRedo: true,
  showDirection: false,
  showSearchButton: true,
  showSubscript: true,
  showSuperscript: true,
  showClipboardCut: false,
  showClipboardCopy: false,
  showClipboardPaste: false,
*/
class QuillToolbarConfigs {
  static const minimal = QuillSimpleToolbarConfig(
    multiRowsDisplay: true,
    showDividers: false,
    showFontFamily: false,
    showFontSize: false,
    showBoldButton: true,
    showItalicButton: true,
    showSmallButton: false,
    showUnderLineButton: true,
    showLineHeightButton: true,
    showStrikeThrough: true,
    showInlineCode: false,
    showColorButton: true,
    showBackgroundColorButton: true,
    showClearFormat: true,
    showAlignmentButtons: true,
    showLeftAlignment: true,
    showCenterAlignment: true,
    showRightAlignment: true,
    showJustifyAlignment: true,
    showHeaderStyle: true,
    showListNumbers: true,
    showListBullets: true,
    showListCheck: true,
    showCodeBlock: false,
    showQuote: false,
    showIndent: false,
    showLink: false,
    showUndo: false,
    showRedo: false,
    showDirection: false,
    showSearchButton: false,
    showSubscript: false,
    showSuperscript: false,
    showClipboardCut: false,
    showClipboardCopy: false,
    showClipboardPaste: false,
  );

  static const basic = QuillSimpleToolbarConfig(
    showBoldButton: true,
    showItalicButton: true,
    showUnderLineButton: true,
    showListBullets: true,
    showListNumbers: true,

    showColorButton: false,
    showHeaderStyle: false,
    showAlignmentButtons: false,
  );

  static const advanced = QuillSimpleToolbarConfig(
    showColorButton: true,
    showBackgroundColorButton: true,
    showAlignmentButtons: true,
    showHeaderStyle: true,
  );


}
